using FptuGradingSystem.Application;
using FptuGradingSystem.Application.Common.Interfaces;
using FptuGradingSystem.Infrastructure;
using FptuGradingSystem.Infrastructure.Data;
using FptuGradingSystem.API.GrpcClients;
using FptuGradingSystem.API.Middleware;
using Grpc.Net.Client;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// Enable unencrypted HTTP/2 for gRPC inter-service calls
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

// Add Layers Services
builder.Services.AddApplicationServices();
builder.Services.AddInfrastructureServices(builder.Configuration);

// Register gRPC client for calling GradingCalculator service & DocumentReader service
var grpcAddress = builder.Configuration["GrpcService:Address"] ?? "http://localhost:5001";
builder.Services.AddSingleton(GrpcChannel.ForAddress(grpcAddress));
builder.Services.AddScoped<IGradingGrpcClient, GradingGrpcClient>();
builder.Services.AddGrpcClient<FptuGradingSystem.GrpcService.DocumentReader.DocumentReaderClient>(options =>
{
    options.Address = new Uri(grpcAddress);
});

// Register gRPC client for calling AuthService UserSyncService
var authGrpcAddress = builder.Configuration["AuthService:GrpcAddress"] ?? "http://auth-api:8080";
builder.Services.AddGrpcClient<FptuGradingSystem.AuthService.Grpc.UserSyncService.UserSyncServiceClient>(options =>
{
    options.Address = new Uri(authGrpcAddress);
});
builder.Services.AddScoped<IUserGrpcClient, FptuGradingSystem.API.GrpcClients.UserGrpcClient>();

// Add Controllers
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.WithOrigins("http://localhost:5173")
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials();
    });
});

builder.Services.AddControllers();
builder.Services.AddSignalR();
builder.Services.AddHostedService<FptuGradingSystem.API.Services.RedisSubscriberService>();

// Add Exception Handler
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();
builder.Services.AddProblemDetails();

// Swagger configuration with JWT Bearer
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "FPTU Grading System API", Version = "v1" });
    
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

// Configure JWT Authentication
var jwtSettings = builder.Configuration.GetSection("JwtSettings");
var secret = jwtSettings.GetValue<string>("Secret");
var issuer = jwtSettings.GetValue<string>("Issuer");
var audience = jwtSettings.GetValue<string>("Audience");

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = issuer,
        ValidAudience = audience,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secret!))
    };
});

builder.Services.AddAuthorization();

var app = builder.Build();

// Ensure DB is created on startup
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    dbContext.Database.EnsureCreated();
    try
    {
        dbContext.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""Classes"" (
                ""Id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""ClassCode"" TEXT NOT NULL
            );
            ALTER TABLE ""ExamClasses"" ADD COLUMN IF NOT EXISTS ""ClassId"" INT NOT NULL DEFAULT 0;
            ALTER TABLE ""ExamClasses"" DROP COLUMN IF EXISTS ""ClassCode"";
        ");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"DB Auto-Init Note: {ex.Message}");
    }

    // Sync Users from AuthService via gRPC (Inter-service Communication)
    try
    {
        var authGrpcAddressSync = builder.Configuration["AuthService:GrpcAddress"] ?? "http://auth-api:8080";
        using var authChannel = GrpcChannel.ForAddress(authGrpcAddressSync, new GrpcChannelOptions { Credentials = Grpc.Core.ChannelCredentials.Insecure });
        var userSyncClient = new FptuGradingSystem.AuthService.Grpc.UserSyncService.UserSyncServiceClient(authChannel);

        var userList = await userSyncClient.GetAllUsersAsync(new FptuGradingSystem.AuthService.Grpc.EmptyRequest());
        if (userList != null && userList.Users.Count > 0)
        {
            foreach (var u in userList.Users)
            {
                var exists = await dbContext.Users.AnyAsync(x => x.Id == u.Id);
                if (!exists)
                {
                    dbContext.Database.ExecuteSqlRaw(
                        "INSERT INTO \"Users\" (\"Id\", \"Username\", \"PasswordHash\", \"Role\", \"Email\", \"FullName\") VALUES ({0}, {1}, '', {2}, {3}, {4})",
                        u.Id, u.Username, u.Role, u.Email, u.FullName);
                }
            }
            Console.WriteLine($"[gRPC Inter-service] Synced {userList.Users.Count} user(s) from AuthService via gRPC successfully!");
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[gRPC UserSync Note] {ex.Message}");
    }
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseExceptionHandler();

app.UseCors("AllowAll");

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.MapHub<FptuGradingSystem.API.Hubs.NotificationHub>("/notificationHub");
app.MapControllers();

app.Run();
