// <auto-generated />
using System;
using FptuGradingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FptuGradingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707151533_RemoveClassSubjectAndAddUniqueConstraintToExamClass")]
    partial class RemoveClassSubjectAndAddUniqueConstraintToExamClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.ExamClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ClassId", "SubjectId", "Semester")
                        .IsUnique();

                    b.ToTable("ExamClasses");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GeneralFeedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GradedById")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("GradedById");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.GradeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int>("RubricCriteriaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("RubricCriteriaId");

                    b.ToTable("GradeDetails");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Rubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Rubrics");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.RubricCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CriteriaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxPoints")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("RubricId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("RubricId");

                    b.ToTable("RubricCriteria");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubjectCode")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamClassId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamClassId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.ExamClass", b =>
                {
                    b.HasOne("FptuGradingSystem.Domain.Entities.Class", "Class")
                        .WithMany("ExamClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FptuGradingSystem.Domain.Entities.User", "Lecturer")
                        .WithMany("ExamClasses")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FptuGradingSystem.Domain.Entities.Subject", "Subject")
                        .WithMany("ExamClasses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Grade", b =>
                {
                    b.HasOne("FptuGradingSystem.Domain.Entities.User", "GradedBy")
                        .WithMany("Grades")
                        .HasForeignKey("GradedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FptuGradingSystem.Domain.Entities.Submission", "Submission")
                        .WithOne("Grade")
                        .HasForeignKey("FptuGradingSystem.Domain.Entities.Grade", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedBy");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.GradeDetail", b =>
                {
                    b.HasOne("FptuGradingSystem.Domain.Entities.Grade", "Grade")
                        .WithMany("GradeDetails")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FptuGradingSystem.Domain.Entities.RubricCriteria", "RubricCriteria")
                        .WithMany("GradeDetails")
                        .HasForeignKey("RubricCriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("RubricCriteria");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Rubric", b =>
                {
                    b.HasOne("FptuGradingSystem.Domain.Entities.Subject", "Subject")
                        .WithMany("Rubrics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.RubricCriteria", b =>
                {
                    b.HasOne("FptuGradingSystem.Domain.Entities.Rubric", "Rubric")
                        .WithMany("Criteria")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Submission", b =>
                {
                    b.HasOne("FptuGradingSystem.Domain.Entities.ExamClass", "ExamClass")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamClass");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Class", b =>
                {
                    b.Navigation("ExamClasses");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.ExamClass", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Grade", b =>
                {
                    b.Navigation("GradeDetails");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Rubric", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.RubricCriteria", b =>
                {
                    b.Navigation("GradeDetails");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Subject", b =>
                {
                    b.Navigation("ExamClasses");

                    b.Navigation("Rubrics");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("FptuGradingSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("ExamClasses");

                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
